### ISSUE TITLE
Unofficial Porting to Fabric

### ISSUE THREAD

**Issue by Emafire003** [elBukkit/EffectLib#17]
Hello there! I wanted to ask if you are ok with me kind-of-porting this library as mod for the Fabric mod loader, since it is a very cool tool and MIT licensed. I've looked into it and, a lot of the code would need to be changed but it's doable. It would be an unofficial port but i would of course still credit the original project and authors with links and stuff. (and I'll leave it opensource of course too)

**Comment by NathanWolf** [comment]
Or course, as long as you keep the MIT license you can do whatever you want with it :)

**Comment by Emafire003** [comment]
Cool, thank you :)
